[project]
id = "become"
name = "Become"

[api]
port = 54321
schemas = ["public"]

[db]
port = 54322

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["become://", "http://localhost:8081"]
jwt_expiry = 3600

[auth.external.apple]
enabled = true

[auth.external.google]
enabled = true
