export { calculateJointAngle, calculateMidpoint, normalize3D } from './geometry';
export { RepStateMachine } from './rep-state-machine';
export { detectCues } from './cue-detection';
export { scoreRep } from './score-calculator';
export { AIR_SQUAT_PROFILE } from './profiles/air-squat';
export { PUSH_UP_PROFILE } from './profiles/push-up';
export { SIT_UP_PROFILE } from './profiles/sit-up';
export { KETTLEBELL_SWING_PROFILE } from './profiles/kettlebell-swing';
export { getProfile } from './profiles/index';
export type { Landmark, ExerciseProfile, JointDefinition, CueRule, RepPhase, PhaseTransition } from './types';
